version: '2'

services:
  hastebin:
    build: .
    ports:
      - "7777:7777"
    networks:
      - docker_hastebin
    restart: always
    volumes:
      - ./haste-server:/app
      - ./config.js:/app/config.js:ro
  redis:
    image: redis:alpine
    networks:
      - docker_hastebin
    restart: always
    volumes:
      - ./redis:/data

networks:
  docker_hastebin:
    driver: bridge
